vich_uploader:
    db_driver: orm

    mappings:
       photos:
           uri_prefix: /upload
           upload_destination: '%kernel.project_dir%/public/images/users_photo'
           namer: Vich\UploaderBundle\Naming\OrignameNamer