vich_uploader:
    db_driver: orm
    mappings:
        photos:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images'
            # namer: Vich\UploaderBundle\Naming\OrignameNamer
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options: {property : 'imageName'}
           # https://github.com/dustin10/VichUploaderBundle/blob/master/docs/usage.md#step-1-configure-an-upload-mapping
           # inject_on_load: false
           # delete_on_update: true
           # delete_on_remove: true